ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB0
USER_LIB_PATH = /home/rems006/Github/rems006-Arduino/Primary/libraries
BOARD_TAG = nano // board type

include /usr/share/arduino/Arduino.mk